Cleanups

diff --git a/.github/workflows/AsteriskCherryPickTest.yml b/.github/workflows/AsteriskCherryPickTest.yml
--- a/.github/workflows/AsteriskCherryPickTest.yml
+++ b/.github/workflows/AsteriskCherryPickTest.yml
@@ -7,7 +7,6 @@ on:
 
 env:
   PR_NUMBER: ${{ github.event.number }}
-  VAR_CHERRY_PICK_TEST_LABEL: ${{vars.CHERRY_PICK_TEST_LABEL}}
 
 jobs:
   GetBranches:
@@ -22,7 +21,6 @@ jobs:
         env:
           GH_TOKEN: ${{ secrets.TOKEN }}
         run: |
-          echo "VCPTL: $VAR_CHERRY_PICK_TEST_LABEL"
           gh pr edit --repo ${{github.repository}} \
             --remove-label ${{vars.CHERRY_PICK_TEST_LABEL}} \
             --remove-label ${{vars.CHERRY_PICK_CHECKS_PASSED_LABEL}} \
@@ -30,7 +28,7 @@ jobs:
             --remove-label ${{vars.CHERRY_PICK_GATES_PASSED_LABEL}} \
             --remove-label ${{vars.CHERRY_PICK_GATES_FAILED_LABEL}} \
             --remove-label ${{vars.CHERRY_PICK_TESTING_IN_PROGRESS}} \
-            ${{env.PR_NUMBER}} || :
+            $PR_NUMBER || :
 
       - name: Get cherry-pick branches
         uses: asterisk/asterisk-ci-actions/GetCherryPickBranchesFromPR@main
@@ -48,7 +46,7 @@ jobs:
         run: |
           gh pr edit --repo ${{github.repository}} \
           --add-label ${{vars.CHERRY_PICK_TESTING_IN_PROGRESS}} \
-          ${{env.PR_NUMBER}} || :
+          $PR_NUMBER || :
 
       - name: GetTestsuitePR
         id: testsuitepr
@@ -103,32 +101,28 @@ jobs:
     steps:
       - name: Check test matrix status
         env:
-          RESULT:    ${{needs.CherryPickTestMatrix.result}}
+          RESULT_UNIT:    ${{needs.CherryPickTestMatrix.result}}
           GH_TOKEN:  ${{ secrets.TOKEN }}
+          IN_PROGRESS_LABEL: ${{vars.CHERRY_PICK_TESTING_IN_PROGRESS}}
+          PASSED_LABEL: ${{vars.CHERRY_PICK_CHECKS_PASSED_LABEL}}
+          FAILED_LABEL: ${{vars.CHERRY_PICK_CHECKS_FAILED_LABEL}}
         run: |
-          case $RESULT in
+          declare -i rc=0
+          case $RESULT_UNIT in
             success)
-              gh pr edit --repo ${{github.repository}} \
-                --remove-label ${{vars.CHERRY_PICK_TESTING_IN_PROGRESS}} \
-                --add-label ${{vars.CHERRY_PICK_CHECKS_PASSED_LABEL}} \
-                ${{env.PR_NUMBER}} || :
-              echo "::notice::All tests passed"
-              exit 0
+              echo "All tests passed"
               ;;
             skipped)
-              gh pr edit --repo ${{github.repository}} \
-                --remove-label ${{vars.CHERRY_PICK_TESTING_IN_PROGRESS}} \
-                --add-label ${{vars.CHERRY_PICK_CHECKS_FAILED_LABEL}} \
-                ${{env.PR_NUMBER}} || :
-              echo "::notice::Unit tests were skipped because of an earlier failure"
-              exit 1
+              echo "::error::One or more tests were skipped because of an earlier failure"
+              rc+=1
               ;;
             *)
-              gh pr edit --repo ${{github.repository}} \
-                --remove-label ${{vars.CHERRY_PICK_TESTING_IN_PROGRESS}} \
-                --add-label ${{vars.CHERRY_PICK_CHECKS_FAILED_LABEL}} \
-                ${{env.PR_NUMBER}} || :
               echo "::error::One or more tests failed ($RESULT)"
-              exit 1
+              rc+=1
           esac
-
+          [ $rc -gt 0 ] && label=$FAILED_LABEL || label=$PASSED_LABEL
+          gh pr edit --repo ${{github.repository}} \
+            --remove-label $IN_PROGRESS_LABEL \
+            --add-label $label \
+            $PR_NUMBER || :
+          exit $rc
diff --git a/.github/workflows/AsteriskRecheckPR.yml b/.github/workflows/AsteriskRecheckPR.yml
--- a/.github/workflows/AsteriskRecheckPR.yml
+++ b/.github/workflows/AsteriskRecheckPR.yml
@@ -64,30 +64,27 @@ jobs:
         env:
           GH_TOKEN:  ${{ secrets.TOKEN }}
           RESULT_UNIT: ${{ needs.PRCheck.result }}
-          TESTS_PASSED: ${{ vars.PR_SUBMIT_TESTS_PASSED }}
-          TESTS_FAILED: ${{ vars.PR_SUBMIT_TESTS_FAILED }}
+          IN_PROGRESS_LABEL: ${{vars.PR_SUBMIT_TESTING_IN_PROGRESS}}
+          PASSED_LABEL: ${{ vars.PR_SUBMIT_TESTS_PASSED }}
+          FAILED_LABEL: ${{ vars.PR_SUBMIT_TESTS_FAILED }}
         run: |
           declare -i rc=0
-          echo "all results: ${{ toJSON(needs.*.result) }}"
           case $RESULT_UNIT in
             success)
-              echo "::notice::Unit/Gate tests passed"
+              echo "All tests passed"
               ;;
             skipped)
-              echo "::error::Unit/Gate tests were skipped because of an earlier failure"
+              echo "::error::One or more tests were skipped because of an earlier failure"
               rc+=1
               ;;
             *)
-              echo "::error::One or more Unit/Gate tests failed ($RESULT_UNIT)"
+              echo "::error::One or more tests failed ($RESULT)"
               rc+=1
           esac
-          
-          label=$TESTS_PASSED
-          if [ $rc != 0 ] ; then
-            label=$TESTS_FAILED
-          fi
+          [ $rc -gt 0 ] && label=$FAILED_LABEL || label=$PASSED_LABEL
           gh pr edit --repo ${{github.repository}} \
-            --remove-label ${{vars.PR_SUBMIT_TESTING_IN_PROGRESS}} \
+            --remove-label $IN_PROGRESS_LABEL \
             --add-label $label \
-              $PR_NUMBER || :
+            ${PR_NUMBER} || :
           exit $rc
+          
